DROP DATABASE IF EXISTS `META_TRADER`;
CREATE SCHEMA `META_TRADER`;
CREATE TABLE `META_TRADER`.`EQ_HS` (
	`idKey` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT  COMMENT '',
	`SYMBOL` VARCHAR(20),
	`DATE_TIME` TIMESTAMP,
	`BID_P` BIGINT,
	`ASK_P` BIGINT,
	`OPEN_P` BIGINT,
	`CLOSE_P` BIGINT,
	`HIGH_P` BIGINT,
	`LOW_P` BIGINT,
	`AVG_P` BIGINT,
	`TOT_VOL` BIGINT,
	`TURNOVER` BIGINT,
	`TRADES_NR` BIGINT,
	PRIMARY KEY (`idKey`) COMMENT '');
	
