DROP DATABASE IF EXISTS `META_TRADER`;
CREATE SCHEMA `META_TRADER`;
CREATE TABLE `META_TRADER`.`EQ_HS` (
	`idKey` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT  COMMENT '',
	`SYMBOL` VARCHAR(20),
	`DATE_TIME` TIMESTAMP,
	`BID_P` BIGINT,
	`ASK_P` BIGINT,
	`OPEN_P` BIGINT,
	`CLOSE_P` BIGINT,
	`HIGH_P` BIGINT,
	`LOW_P` BIGINT,
	`AVG_P` BIGINT,
	`TOT_VOL` BIGINT,
	`TURNOVER` BIGINT,
	`TRADES_NR` BIGINT,
	PRIMARY KEY (`idKey`) COMMENT '');
	
CREATE TABLE `META_TRADER`.`TRADES` (
	`idKey` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT  COMMENT '',
	`SYMBOL` VARCHAR(20),
	`DATE_TIME` TIMESTAMP,
	`ACCOUNID` INT,
	`QTY` BIGINT,
	`PRICE` BIGINT,
	`IS_ENTRY` BOOLEAN,
	`NET_PROFIT` BIGINT,
	`GROSS_PROFIT` BIGINT,
	`COMMISSION` BIGINT,
	PRIMARY KEY (`idKey`) COMMENT '');

CREATE TABLE `META_TRADER`.`ACCOUNTS` (
       `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
       `ACC_NAME` VARCHAR(128),
       `BROKER` VARCHAR(128),
       `USER_ID` VARCHAR(128),
       `PASSWD` VARCHAR(256),
       PRIMARY KEY (`id`) COMMENT '');

CREATE TABLE `META_TRADER`.`INSTRUMENTS` (
       `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
       `SYMBOL` VARCHAR(20),
       PRIMARY KEY (`id`) COMMENT '');
