package org.bergefall.iobase;

/**
 * Thrown when something goes wrong with sequencing.
 * @author ola
 *
 */
public class SequencingException extends RuntimeException {

	/**
	 *  Autogenerated
	 */
	private static final long serialVersionUID = -1685188891305639011L;

	public SequencingException(String msg) {
		super(msg);
	}
}
